-- Migration: create projects and user_projects tables
-- Defines projects table with client name, balance sheet date, and period length.
-- Links projects to users through a user_projects join table.

create table if not exists projects (
  id bigint generated by default as identity primary key,
  client_name text not null,
  balance_sheet_date date not null,
  period_length integer not null check (period_length > 0),
  inserted_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists user_projects (
  user_id uuid references auth.users(id) on delete cascade,
  project_id bigint references projects(id) on delete cascade,
  primary key (user_id, project_id)
);
